apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.first: "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"jupyterhub\"}}"
    #serviceaccounts.openshift.io/oauth-redirectreference.first: "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"${APPLICATION_NAME}\"}}"
    serviceaccounts.openshift.io/oauth-redirecturi.first: "hub/oauth_callback"
    # serviceaccounts.openshift.io/oauth-want-challenges: "false"
  name: jupyterhub-oauth
---
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-oauth
  annotations:
    kubernetes.io/service-account.name: "jupyterhub-oauth" 
type: kubernetes.io/service-account-token 