fullnameOverride: jupyterhub
hub:
  # command: ["jupyterhub", "--config", "/usr/local/etc/jupyterhub/jupyterhub_config.py"]
  image:
    name: image-registry.openshift-image-registry.svc:5000/spark/k8s-hub
    tag: "2.0.0"
  config:
    OpenShiftOAuthenticator:
      oauth_callback_url: https://jupyterhub.apps-crc.testing/hub/oauth_callback
      client_id: system:serviceaccount:spark:jupyterhub-oauth
    JupyterHub:
      authenticator_class: openshift
      admin_access: false
  extraEnv:
    JUPYERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    JUPYTER_ENABLE_LAB: 'true'
    OPENSHIFT_AUTH_API_URL: https://oauth-openshift.apps-crc.testing
    OPENSHIFT_REST_API_URL: https://api.crc.testing:6443
    NO_PROXY: "localhost,127.0.0.1"
  extraConfig:
    ipaddress: |
      from kubernetes import client

      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].env.append(client.V1EnvVar("POD_IP", None, client.V1EnvVarSource(None, client.V1ObjectFieldSelector(None, "status.podIP"))))
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
  networkPolicy:
    enabled: false
proxy: 
  chp:
    networkPolicy:
      enabled: false
singleuser:
  defaultUrl: "/lab"
  uid: 1000
  image:
    name: image-registry.openshift-image-registry.svc:5000/spark/pyspark-notebook
    tag: spark-3.3.1-python-3.9
    pullPolicy: Always
  cmd: ["/usr/local/bin/start.sh", "jupyterhub-singleuser"]
  serviceAccountName: jupyterhub-spark
  storage:
    type: none
    extraVolumes:
      - name: ecc
        hostPath: {}
          # path: "/home/tobias/ecc"
          # path: "/home/{{ tpl .Values.hostUser . }}/ecc"
      - name: ssh
        hostPath: {}
          # path: "/home/tobias/.ssh"
          # path: "/home/{{ tpl .Values.hostUser . }}/.ssh"
      - name: gitconfig
        hostPath: {}
          # path: "/home/TOBIAS/.gitconfig"
          # path: "/home/{{ tpl .Values.hostUser . }}/.gitconfig"
      - name: mysql
        secret:
          secretName: mysql-mysql
          optional: true 
    extraVolumeMounts:
      - mountPath: /home/jovyan/work
        name: ecc
      - mountPath: /home/jovyan/.ssh
        name: ssh
        readOnly: true
      - mountPath: /home/jovyan/.gitconfig
        name: gitconfig
        readOnly: true
      - name: mysql
        mountPath: "/etc/secrets/mysql"
        readOnly: true
  profileList:
    - display_name: "Default"
      default: true
      kubespawner_override:
        args: ['--NotebookApp.allow_origin=*']
        automount_service_account_token: true
        # image_spec: 
  networkPolicy:
    enabled: false
prePuller:
  continuous:
    # NOTE: if used with a Cluster Autoscaler, also add user-placeholders
    enabled: false
  hook:
    enabled: false
# rbac:
#   create: false
